insert into public.customers(name) values ('Sample Hanseong Manufacturing'),('Sample Mirae Mobility'),('Sample Saerom Logistics'),('Sample Daehan Financial'),('Sample Areum Motors'),('Sample Bluepine Properties'),('Sample Onyu Trading'),('Sample Haneul Investment'),('Sample Solmar Hospitality'),('Sample Nuri Services') on conflict(name) do nothing;
insert into public.resources(name,role,primary_skill) values ('Consultant A','Project Manager','M365'),('Engineer B','Technical Consultant','Migration'),('Engineer C','M365 Engineer','M365'),('Security Specialist D','Security Engineer','Security'),('Consultant E','Technical Consultant','M365'),('Consultant F','Technical Consultant','M365'),('Cloud Engineer G','Azure Engineer','Azure OpenAI') on conflict(name) do nothing;
insert into public.projects(customer_id,project_code,name,category,project_type,probability,status,risk_level,phase,progress,start_date,end_date,scope_summary,import_note)
select c.id,v.code,v.name,v.category,'non_resident',v.probability,v.status::public.project_status,v.risk,v.phase,v.progress,v.start_date::date,v.end_date::date,v.scope,v.note from (values
('Sample Hanseong Manufacturing','S-HSM-M365','Microsoft 365 Governance Rollout','M365 Consulting',100,'In Progress','Medium','Delivery',28,'2026-07-01','2026-12-31','Tenant governance, adoption, and rollout planning',null),
('Sample Mirae Mobility','S-MIR-M365','Workplace Migration Pilot','M365 Deployment',50,'Proposal','Low','Proposal',0,'2026-03-01','2026-11-30','Phased productivity-platform migration pilot','Sample schedule intentionally uses non-contiguous months to exercise timeline behavior.'),
('Sample Saerom Logistics','S-SRM-M365','Microsoft 365 Readiness Assessment','M365 Deployment',100,'Confirmed','Medium','Planning',15,'2026-08-01','2026-10-31','Microsoft 365 readiness and implementation planning',null),
('Sample Daehan Financial','S-DHF-SEC','Security Baseline Assessment','Security',100,'Planning','High','Planning',8,'2026-07-01','2026-12-31','Identity and security-control baseline assessment',null),
('Sample Areum Motors','S-ARM-EDU','Microsoft 365 Adoption Program','M365 Education',50,'Proposal','Low','Proposal',0,'2026-06-01','2026-11-30','End-user and administrator adoption program',null),
('Sample Bluepine Properties','S-BLP-M365','Collaboration Platform Modernization','M365 Deployment',100,'In Progress','Medium','Delivery',42,'2026-05-01','2026-11-30','Collaboration-platform modernization and migration',null),
('Sample Onyu Trading','S-ONY-M365','Digital Workplace Discovery','M365 Deployment',50,'Lead','High','Discovery',0,null,null,'Requirements discovery and high-level workplace roadmap',null),
('Sample Haneul Investment','S-HNI-AI','Azure AI Discovery Pilot','Azure OpenAI',100,'In Progress','Medium','Delivery',18,'2026-07-01','2026-12-31','Azure AI proof-of-concept and governance discovery','Sample record uses the normalized Azure AI service name.'),
('Sample Solmar Hospitality','S-SOL-M365','Cloud Workplace Transition','M365 Deployment',50,'Proposal','Medium','Proposal',0,'2026-08-01','2026-10-31','Cloud workplace transition planning',null),
('Sample Nuri Services','S-NUR-M365','Governance and Administrator Workshop','M365 Consulting',50,'Proposal','Low','Discovery',0,null,null,'Governance review and administrator workshop',null)
) v(customer,code,name,category,probability,status,risk,phase,progress,start_date,end_date,scope,note) join public.customers c on c.name=v.customer on conflict(project_code) do nothing;
