insert into public.customers(name) values ('Sample Hanseong Manufacturing'),('Sample Mirae Mobility'),('Sample Saerom Logistics'),('Sample Daehan Financial'),('Sample Areum Motors'),('Sample Bluepine Properties'),('Sample Onyu Trading'),('Sample Haneul Investment'),('Sample Solmar Hospitality'),('Sample Nuri Services'),('미래에셋생명'),('젠스타메이트'),('SK렌터카'),('삼양데이타시스템'),('현대엔지니어링'),('현대차그룹'),('CJ대한통운'),('비엔세라'),('태용엔지니어링'),('보성공업'),('파라다이스'),('영원무역홀딩스'),('한양건설'),('웰컴페이먼츠'),('우미건설'),('엘릭서 스튜디오'),('WIZCNS'),('포스코DX'),('현대무브'),('KB캐피탈'),('종근당건강'),('에임드 바이오'),('엘리시젠'),('Hyundai Mobis US'),('Samsung Securities'),('KIA US'),('위아공작기계') on conflict(name) do nothing;
insert into public.resources(name,role,primary_skill) values ('Consultant A','Project Manager','M365'),('Engineer B','Technical Consultant','Migration'),('Engineer C','M365 Engineer','M365'),('Security Specialist D','Security Engineer','Security'),('Consultant E','Technical Consultant','M365'),('Consultant F','Technical Consultant','M365'),('Cloud Engineer G','Azure Engineer','Azure OpenAI'),('설용환','Technical Consultant','M365'),('김태후','Technical Consultant','M365') on conflict(name) do nothing;
insert into public.projects(customer_id,project_code,name,category,project_type,probability,status,risk_level,phase,progress,start_date,end_date,scope_summary,import_note)
select c.id,v.code,v.name,v.category,v.project_type,v.probability,v.status::public.project_status,v.risk,v.phase,v.progress,v.start_date::date,v.end_date::date,v.scope,v.note from (values
('Sample Hanseong Manufacturing','S-HSM-M365','Microsoft 365 Governance Rollout','M365 Consulting','non_resident',100,'In Progress','Medium','Delivery',28,'2026-07-01','2026-12-31','Tenant governance, adoption, and rollout planning',null),
('Sample Mirae Mobility','S-MIR-M365','Workplace Migration Pilot','M365 Deployment','non_resident',50,'Proposal','Low','Proposal',0,'2026-03-01','2026-11-30','Phased productivity-platform migration pilot','Sample schedule intentionally uses non-contiguous months to exercise timeline behavior.'),
('Sample Saerom Logistics','S-SRM-M365','Microsoft 365 Readiness Assessment','M365 Deployment','non_resident',100,'Confirmed','Medium','Planning',15,'2026-08-01','2026-10-31','Microsoft 365 readiness and implementation planning',null),
('Sample Daehan Financial','S-DHF-SEC','Security Baseline Assessment','Security','non_resident',100,'Planning','High','Planning',8,'2026-07-01','2026-12-31','Identity and security-control baseline assessment',null),
('Sample Areum Motors','S-ARM-EDU','Microsoft 365 Adoption Program','M365 Education','non_resident',50,'Proposal','Low','Proposal',0,'2026-06-01','2026-11-30','End-user and administrator adoption program',null),
('Sample Bluepine Properties','S-BLP-M365','Collaboration Platform Modernization','M365 Deployment','non_resident',100,'In Progress','Medium','Delivery',42,'2026-05-01','2026-11-30','Collaboration-platform modernization and migration',null),
('Sample Onyu Trading','S-ONY-M365','Digital Workplace Discovery','M365 Deployment','non_resident',50,'Lead','High','Discovery',0,null,null,'Requirements discovery and high-level workplace roadmap',null),
('Sample Haneul Investment','S-HNI-AI','Azure AI Discovery Pilot','Azure OpenAI','non_resident',100,'In Progress','Medium','Delivery',18,'2026-07-01','2026-12-31','Azure AI proof-of-concept and governance discovery','Sample record uses the normalized Azure AI service name.'),
('Sample Solmar Hospitality','S-SOL-M365','Cloud Workplace Transition','M365 Deployment','non_resident',50,'Proposal','Medium','Proposal',0,'2026-08-01','2026-10-31','Cloud workplace transition planning',null),
('Sample Nuri Services','S-NUR-M365','Governance and Administrator Workshop','M365 Consulting','non_resident',50,'Proposal','Low','Discovery',0,null,null,'Governance review and administrator workshop',null),
('미래에셋생명','MZC-MAL-M365','업무망 M365 구축 프로젝트','M365 Deployment','resident',0,'Proposal','Low','Proposal',0,'2026-08-01','2027-01-31','Microsoft 365 workplace deployment proposal',null),
('젠스타메이트','MZC-GEN-M365','M365 Document Approval Automation','M365 Consulting','non_resident',0,'In Progress','Low','Delivery',0,null,null,'Microsoft 365 document approval automation',null),
('SK렌터카','MZC-SKR-GCP','GWS BigQuery Dashboard Build','Google Cloud','non_resident',0,'Qualified','Low','Scoping',0,null,null,'Google Workspace reporting dashboard build','Customer requested target implementation before 2026-09-07; support scope and effort remain under review.'),
('SK렌터카','MZC-SKR-GCP-MSP','GCP MSP Onboarding','Google Cloud','non_resident',0,'Qualified','Medium','Scoping',0,'2026-09-01',null,'GCP contract and MSP onboarding aligned to Google Workspace go-live planning','GCP-centered MSP participation is expected around the Google Workspace transition; detailed owner and operating scope remain under review.'),
('SK렌터카','MZC-SKR-MSP-ASMT','AWS and Azure MSP Assessment','M365 Consulting','non_resident',0,'Qualified','Medium','Assessment Planning',0,'2026-08-01','2026-12-31','AWS and Azure usage analysis, FinOps cost optimization review, and MSP transition planning','FinOps support is required for the detailed review; CMU and MSU participation is being coordinated for a direct customer meeting around 2026-08-19 or 2026-08-20 before a possible 2027-01 MSP transition.'),
('삼양데이타시스템','MZC-SAM-EXO','Exchange Online Transition','M365 Migration','non_resident',0,'Proposal','Low','Proposal',0,null,null,'Exchange Online transition proposal',null),
('현대엔지니어링','MZC-HEC-COP','M365 Copilot PoC and Education Program','Copilot','non_resident',0,'Qualified','Medium','Scoping',0,null,'2026-11-30','M365 Copilot PoC support with offline experience day, online basic training, mission challenge, advanced education, and case workshop planning','Offline Copilot experience day is on hold after purchase timing delay; the prior 2026-08-26 support visit should be ignored until a new date is confirmed.'),
('현대차그룹','MZC-HMG-COP','M365 Copilot Adoption Program','Copilot','non_resident',0,'In Progress','Low','Support Launch',0,'2026-08-10',null,'Microsoft 365 Copilot adoption program','Copilot inquiry support is scheduled to start through Teams at 2026-08-10 09:00 after channel setup.'),
('CJ대한통운','MZC-CJL-M365','미국법인 Microsoft 365 전환','M365 Migration','non_resident',0,'Planning','Low','Planning',0,null,null,'Google Workspace to Microsoft 365 transition planning',null),
('CJ대한통운','MZC-CJL-VN-M365','Vietnam Subsidiary Microsoft 365 Migration','M365 Migration','non_resident',0,'Planning','Medium','Effort Review',0,null,null,'Microsoft 365 migration planning for Vietnam subsidiary users and workloads','Initial effort was estimated at 3.0 M/M for about 600 users; final schedule depends on workload, data-volume, cutover, and local IT readiness confirmation.'),
('비엔세라','MZC-BNC-M365','Microsoft 365 Assessment and Consulting','M365 Consulting','non_resident',0,'In Progress','Low','Delivery',0,'2026-07-15',null,'Microsoft 365 assessment and consulting',null)
,('태용엔지니어링','MZC-TAE-M365','Microsoft 365 Workplace Build Assessment','M365 Deployment','non_resident',0,'Lead','Low','Discovery',0,null,null,'Microsoft 365 workplace, document management, workflow, and migration assessment',null)
,('보성공업','MZC-BOS-M365','Hiworks to Microsoft 365 Migration Scoping','M365 Migration','non_resident',0,'Proposal','Low','Scoping',0,null,null,'Hiworks to Microsoft 365 migration and security-readiness scoping',null)
,('파라다이스','MZC-PAR-SEC','Microsoft 365 Security and Operations Workshop','Security','non_resident',0,'Qualified','Low','Workshop',0,'2026-07-24','2026-07-24','Microsoft 365 security and operations assessment workshop',null)
,('영원무역홀딩스','MZC-YOH-M365','Microsoft 365 Optimization Consulting','M365 Consulting','non_resident',0,'Confirmed','Low','Planning',0,'2026-09-01',null,'Microsoft 365 optimization consulting, security design, PoC, and rollout roadmap',null)
,('영원무역홀딩스','MZC-YOH-TEAMS-OS','Overseas Subsidiary Teams Deployment Proposal','M365 Deployment','non_resident',0,'Proposal','Medium','Proposal',0,null,null,'Teams deployment structure proposal for overseas subsidiaries, including account setup, licensing, and operating model review','Customer requested a deployment structure proposal for 277 overseas subsidiary users; response is targeted by 2026-08-18.')
,('한양건설','MZC-HYC-SEC','V3 Endpoint Security Quote','Security','non_resident',0,'Confirmed','Low','Ordered',0,null,null,'V3 endpoint and server security license quote','Purchase order was received for the endpoint security license quote. Financial details intentionally omitted.')
,('웰컴페이먼츠','MZC-WP-MIP','DRM to Microsoft MIP Transition Assessment','Security','non_resident',0,'Qualified','Medium','Discovery',0,null,null,'Microsoft Purview Information Protection transition assessment, including legacy-system integration, audit logging, and third-party gateway fit review','Initial customer meeting identified MIP migration and legacy integration considerations; executive proposal session is planned but not dated.')
,('우미건설','MZC-WOOMI-SP-STG','SharePoint Storage Consulting','M365 Consulting','non_resident',0,'Qualified','Medium','Meeting Coordination',0,null,null,'SharePoint storage consulting for 50TB on-premises storage, including capacity increase or third-party solution direction review','Customer requested a meeting for Microsoft account handoff and SharePoint storage consulting; candidate dates are 2026-08-18, 2026-08-19 morning, or 2026-08-20, but no final schedule is confirmed.')
,('엘릭서 스튜디오','MZC-ELX-SEC','Security Workplace Build Scoping','Security','non_resident',0,'Qualified','Medium','Meeting Coordination',0,null,null,'Microsoft 365 security workplace design with Intune, Entra ID, Zscaler, endpoint DLP, and segmented office network requirements','Customer requested an on-site discussion for new office security architecture; available dates are under coordination.')
,('WIZCNS','MZC-WIZ-AI','AI OA Helpdesk Service Desk Build','Azure OpenAI','non_resident',0,'Lead','Medium','Discovery',0,null,null,'AI helpdesk with LLM/RAG, Teams, Microsoft 365, AD, and ITAM integration',null)
,('포스코DX','MZC-PDX-SEC','Microsoft Purview Audit Training','Security','non_resident',0,'Qualified','Low','Workshop',0,'2026-08-07','2026-08-07','SharePoint Online and OneDrive audit training with Purview audit log, eDiscovery, role, and test-tenant preparation guidance','Offline training remains scheduled for 2026-08-07 14:00-16:00. Customer requested audit-included content; Teams audit content is separated for a later session.')
,('현대무브','MZC-HMOVE-M365','M365 Policy Configuration Review','M365 Consulting','non_resident',0,'In Progress','Low','Policy Review',0,'2026-07-30',null,'Microsoft 365 security policy configuration review, including MIP labels and Conditional Access policy alignment','Policy workbook and explanatory material sent for customer review; financial details intentionally omitted.')
,('KB캐피탈','MZC-KBC-COP-E5','M365 Copilot and E5 Security Assessment','Copilot','non_resident',0,'Lead','Medium','Quote Request',0,null,null,'M365 Copilot adoption scoping with E5 upgrade, security architecture, and financial-sector security review preparation','Customer requested a quote for Copilot adoption planning and related E5/security assessment work; contract amount and contact details intentionally omitted.')
,('종근당건강','MZC-CKDH-COP-TRIAL','M365 Copilot Trial Engagement','Copilot','non_resident',0,'Qualified','Low','Trial Coordination',0,null,null,'M365 Copilot trial-license engagement and customer approval follow-up','Customer approval for trial-license progression was reported; contact details intentionally omitted.')
,('에임드 바이오','MZC-AIMED-M365','Microsoft 365 Workplace Build Scoping','M365 Deployment','non_resident',0,'Lead','Medium','Quote Request',0,null,null,'Microsoft 365 tenant setup, Windows standardization, policy configuration, and workplace security scoping','New customer requested a build quote for about 60 users; financial details intentionally omitted.')
,('엘리시젠','MZC-ELIS-COP','M365 and Copilot Quote Follow-up','Copilot','non_resident',0,'Proposal','Low','Quote Sent',0,null,null,'M365 licensing and Copilot-related proposal follow-up','Quote materials were sent for M365 project and licensing scope; financial details intentionally omitted.')
,('Hyundai Mobis US','MZC-HMB-COP','Azure and Copilot Deployment','Copilot','non_resident',0,'Qualified','Medium','Scoping',0,'2026-08-01',null,'Azure and Microsoft 365 Copilot deployment coordination','Near-term PO timing indicated for early August; delivery details remain pending.')
,('Samsung Securities','MZC-SAMSC-COP','M365 Copilot Workplace Network Deployment','Copilot','non_resident',0,'Confirmed','Medium','PMS Registration',0,'2026-06-08','2026-11-30','Microsoft 365 Copilot workplace network deployment with PMS and timecard management','Billable PMS registration and project administration owner confirmed; financial details intentionally omitted.')
,('KIA US','MZC-KIA-COP','M365 Copilot Training Plan','Copilot','non_resident',0,'Qualified','Medium','Scoping',0,'2026-09-09',null,'Microsoft 365 Copilot one-hour lecture-style training plan for executive, regional, coordinator, and corporate user groups','Customer prefers one-hour lecture sessions first, with interactive training later. Proposed plan remains 8-9 one-hour sessions for about 565 users; 4 PM PST is acceptable for one session per group, while 5 PM PST was rejected and another morning or early-afternoon PST slot is needed. Delivery is available from 2026-09-09 onward; 2026-09-24 through 2026-09-26 should be excluded.')
,('위아공작기계','MZC-WIA-ARCHIVE','M365 Archive Data Restore Support','M365 Consulting','non_resident',0,'Qualified','High','Order Request',0,'2026-08-12',null,'Microsoft 365 archive data restore support using temporary archive restore licensing','Restore support requires a short-term license order to avoid archive data loss; order approval and execution timing remain pending.')) v(customer,code,name,category,project_type,probability,status,risk,phase,progress,start_date,end_date,scope,note) join public.customers c on c.name=v.customer on conflict(project_code) do nothing;

update public.projects p
set project_manager_id = r.id
from (values
('MZC-GEN-M365','설용환'),
('MZC-HMG-COP','김태후'),
('MZC-CJL-M365','설용환'),
('MZC-CJL-VN-M365','설용환'),
('MZC-BNC-M365','김태후'),
('MZC-HMOVE-M365','설용환')
) m(code,manager_name)
join public.resources r on r.name = m.manager_name
where p.project_code = m.code;
