import { useEffect, useMemo, useState, type FormEvent, type ReactNode } from 'react'
import { Link, NavLink, Navigate, Route, Routes, useLocation, useParams } from 'react-router-dom'
import { AlertTriangle, BarChart3, Bell, BriefcaseBusiness, Building2, CalendarDays, ChevronRight, CircleHelp, Download, FileBarChart, LayoutDashboard, LogOut, Menu, Moon, Plus, Search, Settings, Sun, Users, X } from 'lucide-react'
import { Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { projects, resources } from './data'
import { activeInMonth, allocationFor, projectWarnings, toCsv } from './lib/portfolio'
import { isSupabaseConfigured, supabase } from './lib/supabase'
import type { Project, RiskLevel } from './types'

const statusKo: Record<string,string> = { Lead:'리드', Proposal:'제안', Confirmed:'확정', Planning:'계획', 'In Progress':'진행 중', 'At Risk':'위험', Completed:'완료', 'On Hold':'보류' }
const colors = ['#0b69a3','#16a085','#7c5ce5','#e69a2d','#d9534f','#5b6b7b']

function AuthGate({children}:{children:ReactNode}) {
  const [ready,setReady] = useState(!isSupabaseConfigured)
  const [signedIn,setSignedIn] = useState(!isSupabaseConfigured)
  useEffect(()=>{
    const client = supabase
    if (!client) return
    void client.auth.getSession().then(({data})=>{ setSignedIn(Boolean(data.session)); setReady(true) })
    const {data} = client.auth.onAuthStateChange((_event,session)=>setSignedIn(Boolean(session)))
    return ()=>data.subscription.unsubscribe()
  },[])
  if (!ready) return <div className="center-state">세션 확인 중…</div>
  if (!signedIn) return <Login />
  return <>{children}</>
}

function Login() {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false)
  async function submit(e:FormEvent){e.preventDefault(); if(!supabase)return; setBusy(true); const {error:authError}=await supabase.auth.signInWithPassword({email,password}); setError(authError?.message ?? ''); setBusy(false)}
  return <main className="login-shell"><section className="login-brand"><div className="brand-mark">P</div><p className="eyebrow">PROJECT OPERATIONS</p><h1>프로젝트의 현재와<br/>다음을 한눈에.</h1><p>고객, 일정, 인력과 리스크를 하나의 안전한 포트폴리오에서 관리하세요.</p></section><form className="login-card" onSubmit={submit}><p className="eyebrow">SECURE WORKSPACE</p><h2>로그인</h2><p className="muted">승인된 계정으로 포트폴리오에 접속합니다.</p><label>이메일<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>비밀번호<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p className="form-error">{error}</p>}<button className="primary wide" disabled={busy}>{busy?'확인 중…':'로그인'}</button><button type="button" className="text-button" onClick={()=>void supabase?.auth.resetPasswordForEmail(email)} disabled={!email}>비밀번호 재설정</button></form></main>
}

const nav = [
  ['/', '대시보드', LayoutDashboard], ['/projects','프로젝트',BriefcaseBusiness], ['/schedule','일정',CalendarDays], ['/resources','리소스',Users], ['/customers','고객사',Building2], ['/reports','리포트',FileBarChart], ['/settings','설정',Settings],
] as const

function Shell() {
  const [open,setOpen]=useState(false); const [dark,setDark]=useState(false); const location=useLocation()
  useEffect(()=>setOpen(false),[location.pathname])
  return <div className={dark?'app dark':'app'}><aside className={open?'sidebar open':'sidebar'}><div className="logo"><div className="brand-mark small">P</div><div><strong>Portfolio</strong><span>Delivery Office</span></div><button className="icon mobile-only" onClick={()=>setOpen(false)} aria-label="메뉴 닫기"><X/></button></div><nav>{nav.map(([to,label,Icon])=><NavLink key={to} to={to} end={to==='/'}><Icon/><span>{label}</span></NavLink>)}</nav><div className="side-foot"><div className="avatar">AD</div><div><strong>관리자</strong><span>{isSupabaseConfigured?'Secure workspace':'읽기 전용 미리보기'}</span></div></div></aside><div className="main"><header><button className="icon mobile-only" onClick={()=>setOpen(true)} aria-label="메뉴 열기"><Menu/></button><div className="global-search"><Search/><input placeholder="프로젝트, 고객사, 담당자 검색" aria-label="전체 검색"/></div><div className="header-actions"><span className="sync">샘플 데이터</span><button className="icon" onClick={()=>setDark(!dark)} aria-label="테마 변경">{dark?<Sun/>:<Moon/>}</button><button className="icon"><Bell/></button>{supabase&&<button className="icon" onClick={()=>void supabase?.auth.signOut()} aria-label="로그아웃"><LogOut/></button>}</div></header><main className="content"><Routes><Route path="/" element={<Dashboard/>}/><Route path="/projects" element={<Projects/>}/><Route path="/projects/:id" element={<ProjectDetail/>}/><Route path="/schedule" element={<Schedule/>}/><Route path="/resources" element={<Resources/>}/><Route path="/customers" element={<Customers/>}/><Route path="/reports" element={<Reports/>}/><Route path="/settings" element={<SettingsPage/>}/><Route path="*" element={<Navigate to="/" replace/>}/></Routes></main></div>{open&&<button className="backdrop" onClick={()=>setOpen(false)} aria-label="메뉴 닫기"/>}</div>
}

function PageTitle({eyebrow,title,desc,action}:{eyebrow:string,title:string,desc:string,action?:ReactNode}){return <div className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function Badge({children,tone='blue'}:{children:ReactNode,tone?:string}){return <span className={`badge ${tone}`}>{children}</span>}
function statusTone(status:string){return status==='In Progress'?'teal':status==='Confirmed'?'blue':status==='Proposal'?'purple':status==='At Risk'?'red':'gray'}
function riskTone(risk:RiskLevel){return risk==='High'?'red':risk==='Medium'?'amber':'teal'}

function Dashboard(){
  const active=projects.filter(p=>['Confirmed','Planning','In Progress'].includes(p.status)); const high=projects.filter(p=>p.risk==='High'); const assigned=new Set(projects.flatMap(p=>p.resources)).size
  const statusData=Object.entries(projects.reduce<Record<string,number>>((a,p)=>(a[p.status]=(a[p.status]||0)+1,a),{})).map(([name,value])=>({name:statusKo[name],value}))
  const monthly=Array.from({length:12},(_,i)=>({month:`${i+1}월`,projects:projects.filter(p=>activeInMonth(p,i+1)).length}))
  return <><PageTitle eyebrow="EXECUTIVE OVERVIEW" title="프로젝트 포트폴리오" desc="전체 딜리버리 현황과 지금 확인해야 할 항목입니다." action={<Link className="primary" to="/projects"><Plus/> 프로젝트 등록</Link>}/>{!isSupabaseConfigured&&<div className="preview-note"><CircleHelp/><span><strong>읽기 전용 미리보기</strong> — Supabase 환경값을 연결하면 로그인과 실데이터 CRUD가 활성화됩니다.</span></div>}<section className="kpi-grid"><Kpi label="운영 프로젝트" value={active.length} note="확정·계획·진행" trend="+2 이번 달"/><Kpi label="파이프라인" value={projects.filter(p=>p.probability<100).length} note="가중 프로젝트 2.5건"/><Kpi label="고위험" value={high.length} note="즉시 검토 필요" danger/><Kpi label="할당 리소스" value={assigned} note="7명 / 2명 과부하"/></section><section className="dashboard-grid"><article className="panel chart-panel"><PanelHead title="월별 운영 프로젝트" detail="2026년 활성 프로젝트 수"/><ResponsiveContainer width="100%" height={260}><BarChart data={monthly}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="month"/><YAxis allowDecimals={false}/><Tooltip/><Bar dataKey="projects" fill="#0b69a3" radius={[6,6,0,0]}/></BarChart></ResponsiveContainer></article><article className="panel chart-panel"><PanelHead title="상태 분포" detail="전체 10개 프로젝트"/><ResponsiveContainer width="100%" height={260}><PieChart><Pie data={statusData} dataKey="value" nameKey="name" innerRadius={62} outerRadius={94} paddingAngle={3}>{statusData.map((_,i)=><Cell key={i} fill={colors[i%colors.length]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer><div className="legend">{statusData.map((x,i)=><span key={x.name}><i style={{background:colors[i%colors.length]}}/>{x.name} {x.value}</span>)}</div></article><article className="panel attention"><PanelHead title="주의가 필요한 항목" detail="우선순위 기준 자동 분류"/><Attention icon={<AlertTriangle/>} tone="red" title="고위험 프로젝트 2건" text="Sample Daehan Financial, Sample Onyu Trading"/><Attention icon={<Users/>} tone="amber" title="리소스 미지정 2건" text="Sample Onyu Trading, Sample Nuri Services"/><Attention icon={<CalendarDays/>} tone="blue" title="일정 미확정 2건" text="Sample Onyu Trading, Sample Nuri Services"/><Link to="/projects" className="panel-link">전체 프로젝트 검토 <ChevronRight/></Link></article><article className="panel recent"><PanelHead title="최근 프로젝트" detail="최근 업데이트 순"/><ProjectRows rows={[...projects].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).slice(0,5)}/></article></section></>
}
function Kpi({label,value,note,trend,danger}:{label:string,value:number|string,note:string,trend?:string,danger?:boolean}){return <article className={`kpi ${danger?'danger':''}`}><span>{label}</span><strong>{value}</strong><div><small>{note}</small>{trend&&<Badge tone="teal">{trend}</Badge>}</div></article>}
function PanelHead({title,detail}:{title:string,detail:string}){return <div className="panel-head"><div><h2>{title}</h2><p>{detail}</p></div><button className="icon"><Menu/></button></div>}
function Attention({icon,tone,title,text}:{icon:ReactNode,tone:string,title:string,text:string}){return <div className="attention-row"><div className={`signal ${tone}`}>{icon}</div><div><strong>{title}</strong><span>{text}</span></div><ChevronRight/></div>}

function useProjectFilter(){const [query,setQuery]=useState(''); const [status,setStatus]=useState('all'); const filtered=useMemo(()=>projects.filter(p=>(status==='all'||p.status===status)&&`${p.customer} ${p.name} ${p.resources.join(' ')}`.toLowerCase().includes(query.toLowerCase())),[query,status]); return {query,setQuery,status,setStatus,filtered}}
function Projects(){const {query,setQuery,status,setStatus,filtered}=useProjectFilter();function download(){const blob=new Blob([toCsv(filtered)],{type:'text/csv;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='projects-2026.csv';a.click();URL.revokeObjectURL(a.href)}return <><PageTitle eyebrow="PORTFOLIO MANAGEMENT" title="프로젝트" desc={`${filtered.length}개의 프로젝트를 검색하고 관리합니다.`} action={<button className="primary" disabled={!isSupabaseConfigured} title={!isSupabaseConfigured?'Supabase 연결 후 사용 가능':''}><Plus/> 프로젝트 등록</button>}/><div className="toolbar"><label className="search-box"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="프로젝트 또는 고객사 검색"/></label><select value={status} onChange={e=>setStatus(e.target.value)}><option value="all">모든 상태</option>{['Lead','Proposal','Confirmed','Planning','In Progress'].map(s=><option key={s}>{s}</option>)}</select><button className="secondary" onClick={download}><Download/> CSV 내보내기</button></div><div className="panel table-wrap"><table><thead><tr><th>고객사 / 프로젝트</th><th>상태</th><th>확률</th><th>기간</th><th>진행률</th><th>담당 리소스</th><th>위험</th><th></th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td><Link className="project-name" to={`/projects/${p.id}`}><strong>{p.customer}</strong><span>{p.name}</span></Link></td><td><Badge tone={statusTone(p.status)}>{statusKo[p.status]}</Badge></td><td><strong>{p.probability}%</strong></td><td className="nowrap">{p.startDate?.slice(0,7)??'미정'} — {p.endDate?.slice(0,7)??'미정'}</td><td><div className="progress"><i style={{width:`${p.progress}%`}}/></div><small>{p.progress}%</small></td><td><AvatarStack names={p.resources}/></td><td><Badge tone={riskTone(p.risk)}>{p.risk}</Badge></td><td><Link to={`/projects/${p.id}`} className="icon"><ChevronRight/></Link></td></tr>)}</tbody></table>{filtered.length===0&&<div className="empty">조건에 맞는 프로젝트가 없습니다.</div>}</div></>}
function AvatarStack({names}:{names:string[]}){return names.length?<div className="avatars">{names.slice(0,3).map(n=><span key={n} title={n}>{n.slice(0,2).toUpperCase()}</span>)}<small>{names.join(', ')}</small></div>:<Badge tone="amber">미지정</Badge>}
function ProjectRows({rows}:{rows:Project[]}){return <div>{rows.map(p=><Link className="mini-project" to={`/projects/${p.id}`} key={p.id}><div className="project-icon">{p.customer.slice(0,1)}</div><div><strong>{p.customer}</strong><span>{p.name}</span></div><Badge tone={statusTone(p.status)}>{statusKo[p.status]}</Badge><span>{p.updatedAt.slice(5).replace('-','.')}</span><ChevronRight/></Link>)}</div>}

function ProjectDetail(){const {id}=useParams();const p=projects.find(x=>x.id===id);if(!p)return <Navigate to="/projects"/>;const warnings=projectWarnings(p);return <><div className="breadcrumbs"><Link to="/projects">프로젝트</Link><ChevronRight/>{p.customer}</div><PageTitle eyebrow={p.category.toUpperCase()} title={p.name} desc={`${p.customer} · 최근 업데이트 ${p.updatedAt}`} action={<button className="secondary" disabled={!isSupabaseConfigured}>프로젝트 편집</button>}/>{p.importNote&&<div className="preview-note"><CircleHelp/><span>{p.importNote}</span></div>}{warnings.map(w=><div className="warning" key={w}><AlertTriangle/>{w}</div>)}<section className="detail-kpis"><Kpi label="상태" value={statusKo[p.status]} note={p.phase}/><Kpi label="수주 확률" value={`${p.probability}%`} note="수동 조정 가능"/><Kpi label="진행률" value={`${p.progress}%`} note="현재 기준"/><Kpi label="위험 수준" value={p.risk} note="프로젝트 리스크" danger={p.risk==='High'}/></section><section className="detail-grid"><article className="panel prose"><h2>프로젝트 개요</h2><dl><div><dt>고객사</dt><dd>{p.customer}</dd></div><div><dt>프로젝트 매니저</dt><dd>{p.manager}</dd></div><div><dt>기간</dt><dd>{p.startDate??'미정'} — {p.endDate??'미정'}</dd></div><div><dt>범위</dt><dd>{p.scope}</dd></div></dl></article><article className="panel prose"><h2>담당 리소스</h2>{p.resources.length?p.resources.map(n=><div className="resource-line" key={n}><div className="avatar">{n.slice(0,2)}</div><div><strong>{n}</strong><span>할당 50% · 프로젝트 기간</span></div></div>):<div className="empty compact">할당된 리소스가 없습니다.</div>}</article><article className="panel prose span-2"><h2>딜리버리 현황</h2><div className="large-progress"><i style={{width:`${p.progress}%`}}/><span>{p.progress}%</span></div><div className="three-col"><div><span>현재 단계</span><strong>{p.phase}</strong></div><div><span>다음 마일스톤</span><strong>{p.startDate?'상세 계획 확정':'일정 확정 필요'}</strong></div><div><span>마지막 변경</span><strong>{p.updatedAt}</strong></div></div></article></section></>}

function Schedule(){const [year,setYear]=useState(2026);const [prob,setProb]=useState('all');const rows=projects.filter(p=>prob==='all'||p.probability===Number(prob));return <><PageTitle eyebrow="ANNUAL DELIVERY PLAN" title="연간 프로젝트 일정" desc="고객·프로젝트별 작업 기간과 리소스 중복을 월 단위로 확인합니다." action={<button className="secondary" onClick={()=>window.print()}><Download/> 인쇄 / PDF</button>}/><div className="toolbar"><select value={year} onChange={e=>setYear(Number(e.target.value))}><option>2026</option><option>2027</option></select><select value={prob} onChange={e=>setProb(e.target.value)}><option value="all">모든 확률</option><option value="100">100% 확정</option><option value="50">50% 파이프라인</option></select><div className="timeline-legend"><span><i className="bar confirmed"/>확정/진행</span><span><i className="bar pipeline"/>파이프라인</span><span><i className="current-dot"/>현재 월</span></div></div><div className="panel timeline-wrap"><div className="timeline" style={{'--cols':12} as React.CSSProperties}><div className="timeline-head sticky-label">고객사 / 프로젝트</div>{Array.from({length:12},(_,i)=><div key={i} className={`timeline-head ${i===6?'current':''}`}>{i+1}월</div>)}{rows.map(p=><div className="timeline-row" key={p.id}><Link className="timeline-label" to={`/projects/${p.id}`}><strong>{p.customer}</strong><span>{p.name} · {p.resources.join(', ')||'미지정'}</span></Link>{Array.from({length:12},(_,i)=><Link aria-label={`${p.name} ${i+1}월`} to={`/projects/${p.id}`} key={i} className={`month-cell ${i===6?'current':''} ${activeInMonth(p,i+1)?(p.probability===100?'active confirmed':'active pipeline'):''}`}>{activeInMonth(p,i+1)&&<span/>}</Link>)}</div>)}</div></div><p className="footnote">* Sample Mirae Mobility uses intentionally non-contiguous sample work months for timeline verification.</p></>}

function Resources(){const [month,setMonth]=useState(8);return <><PageTitle eyebrow="CAPACITY MANAGEMENT" title="리소스" desc="월별 배정과 가용 용량을 기준으로 과부하를 조기에 확인합니다."/><div className="toolbar"><select value={month} onChange={e=>setMonth(Number(e.target.value))}>{Array.from({length:12},(_,i)=><option value={i+1} key={i}>{i+1}월</option>)}</select></div><section className="resource-grid">{resources.map(r=>{const alloc=allocationFor(r.name,month,projects);return <article className="panel resource-card" key={r.id}><div className="resource-head"><div className="avatar large">{r.name.slice(0,2)}</div><div><h2>{r.name}</h2><p>{r.role}</p></div><Badge tone={alloc>100?'red':alloc>=80?'amber':'teal'}>{alloc>100?'과부하':alloc>=80?'용량 임박':'가용'}</Badge></div><div className="capacity"><span>월간 할당</span><strong>{alloc}%</strong></div><div className="progress"><i style={{width:`${Math.min(alloc,100)}%`}}/></div><div className="resource-meta"><span>주요 기술 <strong>{r.skill}</strong></span><span>프로젝트 <strong>{projects.filter(p=>p.resources.includes(r.name)&&activeInMonth(p,month)).length}</strong></span></div></article>})}</section></>}

function Customers(){const customerRows=Array.from(new Set(projects.map(p=>p.customer))).map(name=>({name,items:projects.filter(p=>p.customer===name)}));return <><PageTitle eyebrow="CUSTOMER PORTFOLIO" title="고객사" desc="고객별 프로젝트 현황과 파이프라인을 한곳에서 관리합니다." action={<button className="primary" disabled={!isSupabaseConfigured}><Plus/> 고객사 등록</button>}/><section className="customer-grid">{customerRows.map(c=><article className="panel customer-card" key={c.name}><div className="customer-logo">{c.name.slice(0,2)}</div><div><h2>{c.name}</h2><p>{c.items.map(x=>x.category).join(' · ')}</p></div><div className="customer-stats"><span>전체 <strong>{c.items.length}</strong></span><span>확정 <strong>{c.items.filter(x=>x.probability===100).length}</strong></span><span>파이프라인 <strong>{c.items.filter(x=>x.probability<100).length}</strong></span></div><Link to={`/projects/${c.items[0].id}`}>프로젝트 보기 <ChevronRight/></Link></article>)}</section></>}

function Reports(){const confirmed=projects.filter(p=>p.probability===100).length;const high=projects.filter(p=>p.risk==='High').length;return <><PageTitle eyebrow="MANAGEMENT REPORTING" title="리포트" desc="현재 포트폴리오 데이터를 바탕으로 한 결정론적 경영 요약입니다."/><article className="panel report-hero"><div><p className="eyebrow">JULY 2026 · EXECUTIVE SUMMARY</p><h2>월간 프로젝트 포트폴리오 요약</h2><p>전체 <strong>{projects.length}개</strong> 프로젝트 중 <strong>{confirmed}개</strong>가 확정되었으며, 나머지는 파이프라인 단계입니다. 고위험 프로젝트는 <strong>{high}개</strong>, 일정 미확정 프로젝트는 <strong>{projects.filter(p=>!p.startDate).length}개</strong>입니다. 8월에는 {projects.filter(p=>activeInMonth(p,8)).length}개 프로젝트가 동시에 운영되어 리소스 배정 검토가 필요합니다.</p></div><button className="secondary" onClick={()=>window.print()}><Download/> PDF로 인쇄</button></article><section className="report-grid">{['월간 포트폴리오','확정 vs 파이프라인','리소스 활용률','위험 및 이슈','고객사 요약','업데이트 준수'].map((x,i)=><article className="panel report-card" key={x}><div className="report-icon"><BarChart3/></div><h2>{x}</h2><p>{i%2===0?'월별 추세와 주요 변화를 경영진 관점에서 확인합니다.':'필터링된 데이터를 표와 요약으로 내보냅니다.'}</p><button className="text-button">리포트 열기 <ChevronRight/></button></article>)}</section></>}

function SettingsPage(){return <><PageTitle eyebrow="WORKSPACE CONTROL" title="설정" desc="인증, 데이터 연결과 포트폴리오 기준을 관리합니다."/><section className="settings-grid"><article className="panel setting"><h2>Supabase 연결</h2><Badge tone={isSupabaseConfigured?'teal':'amber'}>{isSupabaseConfigured?'연결됨':'설정 필요'}</Badge><p>Authentication, PostgreSQL 및 Row Level Security를 사용합니다.</p><code>VITE_SUPABASE_URL</code><code>VITE_SUPABASE_ANON_KEY</code></article><article className="panel setting"><h2>접근 제어</h2><Badge tone="blue">Private</Badge><p>모든 프로젝트 페이지는 기본적으로 인증된 사용자만 접근합니다.</p><ul><li>Admin — 전체 관리</li><li>Manager — 운영 데이터 관리</li><li>Viewer — 읽기 전용</li></ul></article><article className="panel setting"><h2>카테고리</h2><p>M365, Azure, Security, Copilot, Migration 등 운영 분류를 데이터베이스에서 관리할 수 있습니다.</p></article></section></>}

export default function App(){return <AuthGate><Shell/></AuthGate>}
