import type { Project, Resource } from './types'

export const projects: Project[] = [
  { id:'sample-hanseong-governance', customer:'Sample Hanseong Manufacturing', name:'Microsoft 365 Governance Rollout', category:'M365 Consulting', probability:100, status:'In Progress', startDate:'2026-07-01', endDate:'2026-12-31', progress:28, manager:'Consultant A', resources:['Consultant A','Engineer B'], risk:'Medium', scope:'Tenant governance, adoption, and rollout planning', phase:'Delivery', updatedAt:'2026-07-11' },
  { id:'sample-mirae-migration', customer:'Sample Mirae Mobility', name:'Workplace Migration Pilot', category:'M365 Deployment', probability:50, status:'Proposal', startDate:'2026-03-01', endDate:'2026-11-30', progress:0, manager:'Consultant A', resources:['Consultant A','Engineer B'], risk:'Low', scope:'Phased productivity-platform migration pilot', phase:'Proposal', updatedAt:'2026-06-25', workMonths:[3,7,8,11], importNote:'Sample schedule intentionally uses non-contiguous months to exercise timeline behavior.' },
  { id:'sample-saerom-readiness', customer:'Sample Saerom Logistics', name:'Microsoft 365 Readiness Assessment', category:'M365 Deployment', probability:100, status:'Confirmed', startDate:'2026-08-01', endDate:'2026-10-31', progress:15, manager:'Engineer C', resources:['Engineer C'], risk:'Medium', scope:'Microsoft 365 readiness and implementation planning', phase:'Planning', updatedAt:'2026-07-06' },
  { id:'sample-daehan-security', customer:'Sample Daehan Financial', name:'Security Baseline Assessment', category:'Security', probability:100, status:'Planning', startDate:'2026-07-01', endDate:'2026-12-31', progress:8, manager:'Security Specialist D', resources:['Security Specialist D','Engineer B'], risk:'High', scope:'Identity and security-control baseline assessment', phase:'Planning', updatedAt:'2026-07-05' },
  { id:'sample-areum-adoption', customer:'Sample Areum Motors', name:'Microsoft 365 Adoption Program', category:'M365 Education', probability:50, status:'Proposal', startDate:'2026-06-01', endDate:'2026-11-30', progress:0, manager:'Consultant E', resources:['Consultant E'], risk:'Low', scope:'End-user and administrator adoption program', phase:'Proposal', updatedAt:'2026-07-02' },
  { id:'sample-bluepine-modernization', customer:'Sample Bluepine Properties', name:'Collaboration Platform Modernization', category:'M365 Deployment', probability:100, status:'In Progress', startDate:'2026-05-01', endDate:'2026-11-30', progress:42, manager:'Consultant E', resources:['Consultant E','Engineer B'], risk:'Medium', scope:'Collaboration-platform modernization and migration', phase:'Delivery', updatedAt:'2026-07-09' },
  { id:'sample-onyu-discovery', customer:'Sample Onyu Trading', name:'Digital Workplace Discovery', category:'M365 Deployment', probability:50, status:'Lead', startDate:null, endDate:null, progress:0, manager:'미지정', resources:[], risk:'High', scope:'Requirements discovery and high-level workplace roadmap', phase:'Discovery', updatedAt:'2026-06-18' },
  { id:'sample-haneul-ai', customer:'Sample Haneul Investment', name:'Azure AI Discovery Pilot', category:'Azure OpenAI', probability:100, status:'In Progress', startDate:'2026-07-01', endDate:'2026-12-31', progress:18, manager:'Cloud Engineer G', resources:['Cloud Engineer G','Consultant E'], risk:'Medium', scope:'Azure AI proof-of-concept and governance discovery', phase:'Delivery', updatedAt:'2026-07-08', importNote:'Sample record uses the normalized Azure AI service name.' },
  { id:'sample-solmar-workplace', customer:'Sample Solmar Hospitality', name:'Cloud Workplace Transition', category:'M365 Deployment', probability:50, status:'Proposal', startDate:'2026-08-01', endDate:'2026-10-31', progress:0, manager:'Consultant F', resources:['Consultant F','Consultant E'], risk:'Medium', scope:'Cloud workplace transition planning', phase:'Proposal', updatedAt:'2026-07-07' },
  { id:'sample-nuri-workshop', customer:'Sample Nuri Services', name:'Governance and Administrator Workshop', category:'M365 Consulting', probability:50, status:'Proposal', startDate:null, endDate:null, progress:0, manager:'미지정', resources:[], risk:'Low', scope:'Governance review and administrator workshop', phase:'Discovery', updatedAt:'2026-07-04' },
]

export const resources: Resource[] = [
  {id:'consultant-a',name:'Consultant A',role:'Project Manager',skill:'M365',capacity:100},
  {id:'engineer-b',name:'Engineer B',role:'Technical Consultant',skill:'Migration',capacity:100},
  {id:'engineer-c',name:'Engineer C',role:'M365 Engineer',skill:'M365',capacity:100},
  {id:'security-specialist-d',name:'Security Specialist D',role:'Security Engineer',skill:'Security',capacity:100},
  {id:'consultant-e',name:'Consultant E',role:'Technical Consultant',skill:'M365',capacity:100},
  {id:'consultant-f',name:'Consultant F',role:'Technical Consultant',skill:'M365',capacity:100},
  {id:'cloud-engineer-g',name:'Cloud Engineer G',role:'Azure Engineer',skill:'Azure OpenAI',capacity:100},
]
